from typing import Any, Protocol
from domain.entities.readme_entity import ReadmeData


class IReadmeRepository(Protocol):
    async def save(self, link_origin: str) -> int: ...
    async def list_all(self) -> list[ReadmeData]: ...
    async def get_by_id(self, id: int) -> ReadmeData | None: ...
    async def get_by_tag(self, tag_name: str) -> list[ReadmeData]: ...
    async def update(self, id: int, data: dict[str, Any]) -> ReadmeData | None: ...
    async def delete(self, id: int) -> bool: ...
    


